import Head from 'next/head'
import Image from 'next/image'


import Blog from '../components/Blog'
import { Inter } from '@next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})
export default function Home() {
  return (
    <>
      <Head>

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`font-inter`}>
       
       <div className=''></div>
        <div className='m-24  grid grid-cols-3 gap-4'>
<Blog title={'first blog'}></Blog>
<Blog title={'second blog'}></Blog>
        </div>
      </main>
    </>
  )
}
